rules:
- actions:
  - python: "from pathlib import Path\n\ntarget = Path(path)\nroot = Path(location)\n\
      \nif target.exists():\n    target.rmdir()\n\nparent = target.parent\nwhile parent.is_dir()\
      \ and parent != root and not any(parent.iterdir()):\n    parent.rmdir()\n  \
      \  parent = parent.parent"
  filters:
  - empty
  locations:
  - exclude_dirs:
    - important
    - backup
    path: D:\Downloads\test\another
  name: 清理空目录
  subfolders: true
  targets: dirs
