rules:
- actions:
  - move: '{location}/[video]/{path.relative_to(location)}'
  filters:
  - extension:
    - mp4
    - avi
    - mkv
    - mov
    - wmv
    - flv
    - webm
    - nov
  locations:
  - path: D:\Downloads\test
  name: Move Videos to [video] Folder
  subfolders: true
