# config.toml for organizef

# Define profiles that combine rules
[profiles.clean_empty]
description = "清理空目录"
rules = [
    { id = "clean_empty_dirs", enabled = true, params = { exclude_dirs = ["important", "backup"] } }
]


[profiles.clean_comprehensive]
description = "综合清理（空目录+备份文件+临时文件夹+垃圾文件）"
rules = [
    { id = "clean_empty_dirs", enabled = true, params = { exclude_dirs = ["important", "backup"] } },
    { id = "clean_backup_files", enabled = true, params = {} },
    { id = "clean_temp_folders", enabled = true, params = {} },
    { id = "clean_trash", enabled = true, params = {} }
]

[profiles.dissolve_single_video]
description = "解散单视频文件夹"
rules = [
    { id = "dissolve_single_video", enabled = true, params = { video_extensions = ["mp4", "avi", "mkv", "mov", "wmv", "flv", "webm", "nov"] } }
]

[profiles.dissolve_single_archive]
description = "解散单压缩包文件夹"
rules = [
    { id = "dissolve_single_archive", enabled = true, params = { archive_extensions = ["zip", "rar", "7z", "cbz", "cbr"] } }
]

[profiles.dissolve_direct]
description = "直接解散指定文件夹"
rules = [
    { id = "dissolve_direct", enabled = true, params = { dissolve_folder_names = ["target_folder"] } }
]

[profiles.move_videos]
description = "移动视频文件到 [video] 文件夹"
rules = [
    { id = "move_videos", enabled = true, params = { video_extensions = ["mp4", "avi", "mkv", "mov", "wmv", "flv", "webm", "nov"] } }
]

