# config.toml for organizef

# Define profiles that combine rules
[profiles.clean_empty]
description = "清理空目录"
rules = [
    { id = "clean_empty_dirs", enabled = true, params = { exclude_dirs = ["important", "backup"] } }
]

[profiles.dissolve_media]
description = "解散单媒体文件夹"
rules = [
    { id = "dissolve_single_media", enabled = true, params = { extensions = [".jpg", ".png", ".mp4"] } }
]

[profiles.move_videos]
description = "移动视频文件到 [video] 文件夹"
rules = [
    { id = "move_videos", enabled = true, params = { video_extensions = ["mp4", "avi", "mkv", "mov", "wmv", "flv", "webm", "nov"] } }
]