# config.toml for organizef

# Define profiles that combine rules
[profiles.clean_empty]
description = "清理空目录"
tags = ["Clean"]
rules = [
    { id = "clean_empty_dirs", enabled = true, params = { exclude_dirs = ["important", "backup"] } }
]


[profiles.clean_comprehensive]
description = "综合清理（空目录+备份文件+临时文件夹+垃圾文件）"
tags = ["Clean"]
rules = [
    { id = "clean_empty_dirs", enabled = true, params = { exclude_dirs = ["important", "backup"] } },
    { id = "clean_backup_files", enabled = true, params = {} },
    { id = "clean_temp_folders", enabled = true, params = {} },
    { id = "clean_trash", enabled = true, params = {} }
]


[profiles.move_videos]
description = "移动视频文件到 [video] 文件夹"
tags = ["Move"]
rules = [
    { id = "move_videos", enabled = true, params = { video_extensions = ["mp4", "avi", "mkv", "mov", "wmv", "flv", "webm", "nov"] } }
]
[profiles.move_gifs]
description = "移动 GIF 文件到 [gif] 文件夹"
tags = ["Move"]
rules = [
    { id = "move_gifs", enabled = true, params = { gif_extensions = ["gif"] } }
]
[profiles.move_images_by_size]
description = "根据图片尺寸移动图片文件"
tags = ["Move", "Clean"]
rules = [
    { id = "move_images_by_size", enabled = true, params = { image_extensions = ["jpg", "jpeg", "png", "gif", "bmp", "tiff", "webp", "avif", "jxl"], max_width = [], max_height = [630], exclude_dirs = ["[organize_images]"] } },
    { id = "clean_empty_dirs", enabled = true, params = { exclude_dirs = ["important", "backup"] } }

]

[profiles.filter_zip_empty_comment]
description = "筛选注释为空的压缩包"
tags = ["Filter", "Zip"]
rules = [
    { id = "filter_zip_empty_comment", enabled = true, params = { zip_extensions = ["zip"], target_folder = "[zip_no_comment]", exclude_dirs = ["[zip_no_comment]"] } }
]

[profiles.classify_manga]
description = "按作品类型分类漫画压缩包（同人志/商业志/单行本/同人动画/同人CG/画集）"
tags = ["Classify", "Manga"]
rules = [
    { id = "classify_manga", enabled = true, params = {
        doujin_keywords = ["doujin", "doujinshi", "同人", "同人志", "同人本", "同人作品", "同人小说", "(C\\d+)", "(COMIC1☆\\d+)", "(例大祭\\d*)", "(FF\\d+)"],
        commercial_keywords = ["commercial", "商业", "商业志", "单行本", "magazine", "magazine", "anthology", "アンソロジー", """([^()]*)COMIC[^()]*""", """([^()]*)快楽天[^()]*""", """([^()]*)Comic[^()]*""", """([^()]*)VOL[^()]*""", """([^()]*)永遠娘[^()]*""", """(.*?\\d+.*?)"""],
        doujin_anime_keywords = ["doujin anime", "同人动画", "同人動畫", "fan animation", "fan made anime", "parody anime"],
        doujin_cg_keywords = ["doujin cg", "同人CG", "同人cg", "fan cg", "fan art", "fan illustration", "parody cg"],
        artbook_keywords = ["artbook", "画集", "art book", "illustration book", "イラスト集", "画册"]
    } }
]


